[package]
name = "vmdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
nix = { version = "0.27.1", features = ["signal"] }
tokio = { version = "1.35.0", features = ["full"] }
